### ISSUE TITLE
Release 19.1 appimage - can't import any images.

### ISSUE THREAD

**Issue by valden80** [kwaroran/RisuAI#121]
If try to import character .png from TavernAI I get this error: "path not allowed on the configured scope: /home ..." (any folder).
When I try to set image for character - it's not set. This time silent - no errors, just not set. 

On previous releases it's been possible.

Manjaro Linux.

Also, with local Oobaboga's text gen UI as backend, generation limited to 80 tokens. Changing option "Max response size" don't change anything.

**Comment by kwaroran** [comment]
I'll close this issue, looks like its related to the tauri framework, and it is unable to fix it until tauri updates it to 2.0.
