### ISSUE TITLE
[Feature Request] Font change option

### ISSUE THREAD

**Issue by llijjo** [kwaroran/RisuAI#139]
I posted a request for another feature a while back, but I think you may have forgotten about it.

I forgot about it too, but another user mentioned it and I remembered.

A font change feature would be nice!

그때 원형 프로필 요청하면서 폰트 바꾸는 옵션도 같이 요청했었는데
아마 폰트는 까먹으신 거 같아서 다시 글 올립니다. 저도 까먹었었는데 딴 분이 언급하셔서 기억났네요....🙄

**Comment by kwaroran** [comment]
It is hard to apply font in browser, dude to security issues.
