### ISSUE TITLE
[Feature Request] Bot card quick deleting Button

### ISSUE THREAD

**Issue by Alwaysfindtheway** [kwaroran/RisuAI#141]
![example](https://files.catbox.moe/jhc89q.PNG)

RisuAI is the best AI chat frontend project of my life.

**Many users have difficulty finding the delete button for bot cards in RisuAI.
My suggestion is to move the Delete Bot Card button to a more direct location, as shown in the image above.**

Thank you very much as always.

(RisuAI는 제 인생 최고의 AI 채팅 프론트엔드 프로젝트입니다.

많은 사용자들이 RisuAI에서 봇 카드의 삭제 버튼을 찾는 것을 어려워 합니다.
저는 이에 대해서 위 이미지와 같이, 봇 카드 삭제 버튼을 더 직관적으로 이동하는 것을 제안합니다.

당신의 노고에 항상 감사합니다.)

**Comment by ljh5650** [comment]
pull request created :)
https://github.com/kwaroran/RisuAI/pull/148

**Comment by kwaroran** [comment]
Even if it's hard to find the delete button, I don't think it's good to add it to the header,
There are already too many buttons in the header, and it becomes still complicated.
