### ISSUE TITLE
API support for KoboldAI

### ISSUE THREAD

**Issue by Devon2311** [kwaroran/RisuAI#15]
There is only support for the "Text Generation Webui" which is pretty cool but many people also use KoboldAI. I use this version for example (because it supports 4bit): https://docs.alpindale.dev/local-installation-(gpu)/koboldai4bit/

Your UI looks soooo good and I really appreciate your efforts you did there!

**Comment by henk717** [comment]
When this get added we can begin promoting this to the KoboldAI community.

**Comment by kwaroran** [comment]
Done #114
