### ISSUE TITLE
How to generate new api key for risu ai? ChatGTP won't work (with $20US subscription) keys generated by ChatGTP won't work with Risu. Where do I get working api key for Risu? Please help

### ISSUE THREAD

**Issue by Voetec61** [kwaroran/RisuAI#150]

**Comment by Alwaysfindtheway** [comment]
This is not the page to ask about how to use RisuAI, but rather to ask about feature suggestions, bugs, etc.
Please go to the official RisuAI disc for help. https://discord.gg/JzP8tB9ZK8
