### ISSUE TITLE
[bug] support firefox/DOMException error

### ISSUE THREAD

**Issue by levecax** [kwaroran/RisuAI#152]
currently, on firefox risu stop after user name input. 
showing  

> Loading Sample bots... 

in window

> Uncaught (in promise) DOMException: The quota has been exceeded.

in console

**Comment by kwaroran** [comment]
> I noticed that the issue was closed but I am still experiencing the bug. Can you please let me know why the issue was closed? can't reproduce this bug?

This is a browser issue. check your browser supports indexeddb or websql
