### ISSUE TITLE
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by Xerah21** [kwaroran/RisuAI#174]
Error
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

When using ElevenLabs. Im using the installer one it was working well the following days but then this error msg constantly pops up each time AI replies using voice. 

I've tried reinstalling it's still the same. What appears to be the problem?

**Comment by karageee** [comment]
Yeah, I'm having the same problem. It seems to be caused by the Character's emotions display.

**Comment by kwaroran** [comment]
This is a ElevenLabs api or api key problem. not directly related to risu, and cannot fix it.
