### ISSUE TITLE
Kobold request parameters

### ISSUE THREAD

**Issue by yuulf** [kwaroran/RisuAI#175]
It seems that not all parameters are sent in the request, in particular max_length, which causes kobold to roll back to the defaults.
https://github.com/kwaroran/RisuAI/blob/89015ac00935f2cb6eda4b293f0360bd05b7b8ea/src/ts/process/request.ts#L510-L516

List of parameters can be viewed here:
https://github.com/LostRuins/koboldcpp/blob/b08b371983932e1f528547b25469a2324d81c835/expose.h#L25-L44

**Comment by joaan-fushi** [comment]
I'm going to take a look at this.
