### ISSUE TITLE
[Feature Request] Eventbook

### ISSUE THREAD

**Issue by KCMhi** [kwaroran/RisuAI#176]
It would be great if there were a separate feature for an event book, which has the same function as the Lorebook.

For Simulation Bot, using Probability Condition of the Lorebook, it is possible to convert various values into HTML GUI and control events.

To trigger meaningful events in chat, inevitably, the Lorebook should be located to Formationg Order at the bottom.

The problem is that this can overwrite other information such as Author's Note or other chats when loading information using keywords from other items in the Lorebook.

Therefore, it becomes impossible to use the Lorebook for its original purpose.

It would be good to have an Event Book specifically for controlling events.

***

Lorebook과 완전히 같은 기능을 하는 Event book이 별개로 추가되었으면 좋겠습니다

시뮬레이션 봇의 경우 로어북의 Probability Condition을 활용해 각종 수치를 HTML로 GUI로 변환해 표시하던가, 이벤트를 제어할 수 있는데

채팅에 유의미한 트리거를 일으키려면 필연적으로 Lorebook을 Formationg Order 가장 밑으로 내려야 합니다.

문제는 이 경우 로어북의 다른 항목의 키워드로 정보를 불러왔을 때 Author's Note나 다른 Chat들을 덮어버리는 경우가 생깁니다.

그렇기 때문에 어쩔 수 없이 로어북의 원래 용도로 쓰는 것이 불가능해집니다

이벤트 제어만을 위한 Lorebook, 즉 Event book이 있었으면 좋겠습니다.

**Comment by kwaroran** [comment]
That would be complex, but I have a plan to rework lorebook and add option to work like that.
