### ISSUE TITLE
[Error] I can't use claude api

### ISSUE THREAD

**Issue by ookk36930** [kwaroran/RisuAI#179]
I am currently using Windows 10 and my browser is Chrome. I tried to chat using the official cloud api key, but the following error popped up.

"<!doctype html><meta charset=\"utf-8\"><meta name=viewport content=\"width=device-width, initial-scale=1\"><title>403</title>403 Forbidden<script defer src=\"https://static.cloudflareinsights.com/beacon.min.js/v52afc6f149f6479b8c77fa569edb01181681764108816\" integrity=\"sha512-jGCTpDpBAYDGNYR5ztKt4BQPGef1P0giN6ZGVUi835kFF88FOmmn8jBQWNgrNd8g/Yu421NdgWhwQoaOPFflDw==\" data-cf-beacon='{\"rayId\":\"7db4ec23aaf2b45e\",\"version\":\"2023.4.0\",\"r\":1,\"token\":\"c622a0c7e1cc41b9b5db4375b44ee190\",\"si\":100}' crossorigin=\"anonymous\"></script>\n"

I wondered if it was due to chrome records or extensions, so I tried turning off all extensions in incognito mode, but the same error occurred. It doesn't seem to have anything to do with vpn. Firefox works fine, but there seems to be a compatibility problem with Chrome.

**Comment by ookk36930** [comment]
Hmm, the same error appears in the mobile Samsung Internet browser.

**Comment by kwaroran** [comment]
This is a bug I were keep working on. It seems it isn't a browser issue, currently reason is unknown. but I'm keep working to fix it.
