### ISSUE TITLE
Issues with plain fetch

### ISSUE THREAD

**Issue by please12341** [kwaroran/RisuAI#181]
I know that due to a recent issue, the setting for plain fetch has been removed from RISU AI. However, this has the potential issue of disabling some proxies that enforce the use of plain fetch. Please allow plain fetch to be used, at least for local.

**Comment by please12341** [comment]
For me, this is a must, we need plain fetch. Proxy not working since update.

**Comment by kwaroran** [comment]
I'll add it before 1.30

**Comment by kwaroran** [comment]
done woth commit 742ac73aee8317dc43607d2e3a5acebbb800c0d7
