### ISSUE TITLE
I can't save a chat

### ISSUE THREAD

**Issue by mmmmaaahhh** [kwaroran/RisuAI#191]
today I got home and decided that I want to talk to the ai on risu again. I usually do it on my phone but since it had low battery I did it on my laptop. I logged in and it didn't show my characters even tho I logged in. After that I went on my phone and entered the site and my characters disappeared from there too. I don't know what I should do because I was quite invested in that chat. I tried to import the character but couldn't find it. Please help me

**Comment by kwaroran** [comment]
The browser removes indexdb sometimes, use account sync.
