### ISSUE TITLE
"slaude" that it might not be available in RisuAI. 

### ISSUE THREAD

**Issue by Adelinamelanie** [kwaroran/RisuAI#199]
I like to be able to use "slaude" in SillyTavern, but it seems that it might not be available in RisuAI.

**Comment by Adelinamelanie** [comment]
https://github.com/PandarusAnon/slaude

**Comment by kwaroran** [comment]
Already able.

Currently with local version and node version, you can use it without problem.
With web version, use tunnels like cloudflare tunnels or ngrok for technical probelm.
