### ISSUE TITLE
Can I compile by myself?

### ISSUE THREAD

**Issue by bolivkazelenayau** [kwaroran/RisuAI#20]
Hey there! Thank you for wonderful project and efforts, I appreciate it a lot.

So, I found an issue in the current build (I've even installed an updated 0.7.3 .msi file) where I can't connect Risu to oogabooga WebUI. As I've learned, it happens because current code version relies on the old API.
I've modified the **database.ts** file to make it run on the new API, but I can't make it work. So I've decided to try to compile it by myself, hence I'm opening this issue.

May you please tell me what dependencies and libraries I need? Or maybe some extensions for Visual Studio? Thank you.

**Comment by kwaroran** [comment]
install node.js, then install pnpm

run pnpm tauri build to build yourself

**Comment by bolivkazelenayau** [comment]
> install node.js, then install pnpm
> 
> then run
> 
> ```
> pnpm i
> pnpm tauri build
> ```
> 
> to build yourself

![image](https://user-images.githubusercontent.com/101355820/236929629-50e7bafd-6a71-472d-9f5c-10babcff5f99.png)

What am I doing wrong?

**Comment by blvckclxud** [comment]
Hello. Was attempting to compile on my machine and got the same error! Impressive work otherwise.

**Comment by asm6788** [comment]
You must install Rust, too. https://www.rust-lang.org/tools/install

**Comment by bolivkazelenayau** [comment]
Hmm. I've installed Rust and Visual C++ Build Tools in Visual Studios and then I was able to build the app, thank you.

I still get this error, though:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/101355820/236978323-fbff6993-2ede-49be-a8c8-5eb4a23c4d2a.png">

And if I change the API address, then I get this error:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/101355820/236978448-f7cce5ca-6320-4595-97ef-88a9cd477e5c.png">

I don't know what's causing it :(

**Comment by asm6788** [comment]
It looks like you are using API incorrect way. Changing the API model or key will be helpful.

**Comment by bolivkazelenayau** [comment]
> It looks like you are using API incorrect way. Changing the API model or key will be helpful.

May you please explain further? I'm using Oogabooga's WebUI within an api mode.

**Comment by asm6788** [comment]
Oh, sorry. I knew you were talking about the Chat API. How about checking 'src/ts/process/stableDiff.ts'

**Comment by asm6788** [comment]
> > It looks like you are using API incorrect way. Changing the API model or key will be helpful.
> 
> May you please explain further? I'm using Oogabooga's WebUI within an api mode.

Oh, sorry. I knew you were talking about the Chat API. How about checking 'src/ts/process/stableDiff.ts'

**Comment by kwaroran** [comment]
had you made url correctly as specified in help button?

**Comment by bolivkazelenayau** [comment]
> had you put url correctly as specified in help button?

Yes I did. I've tried to run it via /v1/generate and via other addresses. Still, no luck. Yet TavernAI works without any issues.

**Comment by kwaroran** [comment]
did you put url 172.0.0.1 or localhost in url?
that will not work

btw, cuz its getting off topic, I closed the issue
