### ISSUE TITLE
AutoMark (Official Plugin) 버그가 있는 것 같습니다.

### ISSUE THREAD

**Issue by bangonicdd** [kwaroran/RisuAI#207]
〈em〉 및 〈/em〉 태그가 다음 리퀘스트에 같이 전송되면서 AI의 출력물에 영향을 주는 것 같습니다.
![image](https://github.com/kwaroran/RisuAI/assets/133192207/083634db-1233-429c-b69e-0a3f3a81698a)

환경 : 웹, 크롬, 윈도10
모델 : 플러그인, 낫뎁, 클로드

**Comment by kwaroran** [comment]
fixed on main branch
