### ISSUE TITLE
[Bug] lorebook bug.

### ISSUE THREAD

**Issue by ookk36930** [kwaroran/RisuAI#211]
There is a bug that when these commands such as @@@user @@@assistant and so on are sent even though they are not activated when used in the lorebook. For example, in the case of a lorebook, I entered an activation key, but the lorebook continues to be sent regardless of the activation key.

한국어

@@@user @@@assistant 등등 이러한 명령어들이 lorebook에 쓰일때 활성화가 되지 않았음에도 보내지는 버그가 있습니다. 예를들어 lorebook의 경우 활성화 키를 입력해놨는데 활성화 키와 전혀 상관없이 lorebook이 계속 보내지는게 있습니다.

**Comment by ookk36930** [comment]
If you have an activation key in the past chat, it seems that the loreBook is sent. was it intended?

**Comment by kwaroran** [comment]
1. The lorebook checks the activation keys not only last chats, but also in he past chats by depth settings
2. @@@user @@@assistant syntax isn't allowed on lorebooks. only works on main/jailbreak/note prompts.
