### ISSUE TITLE
filter error

### ISSUE THREAD

**Issue by Tone1212** [kwaroran/RisuAI#215]
when i tryy talking to some ai i get an error saying "
{"filters":[{"reason":"SAFETY"}],"safetyFeedback":[{"rating":{"category":"HARM_CATEGORY_TOXICITY","probability":"LOW"},"setting":{"category":"HARM_CATEGORY_TOXICITY","threshold":"BLOCK_LOW_AND_ABOVE"}},{"rating":{"category":"HARM_CATEGORY_SEXUAL","probability":"HIGH"},"setting":{"category":"HARM_CATEGORY_SEXUAL","threshold":"BLOCK_MEDIUM_AND_ABOVE"}}]}"
 i dont know how to fix it and if its important im using google palm

**Comment by kwaroran** [comment]
Not Risu Problem, is Model's problem
