### ISSUE TITLE
Create Bot from Ai 오류

### ISSUE THREAD

**Issue by Keoqo** [kwaroran/RisuAI#217]
![image](https://github.com/kwaroran/RisuAI/assets/140310942/45b4ff23-2149-4311-965a-e10368754b46)
![image](https://github.com/kwaroran/RisuAI/assets/140310942/a42e329a-d987-4991-8856-03ae9b3aa881)

해당 오류가 뜹니다.

**Comment by kwaroran** [comment]
Model provider Issue
