### ISSUE TITLE
错误：请求错误："TypeError: Failed to fetch"

### ISSUE THREAD

**Issue by phcha** [kwaroran/RisuAI#222]
在窗口输入内容，发送里报错 ？
错误：请求错误："TypeError: Failed to fetch"，怎么解决这个问题？？？

**Comment by phcha** [comment]
![image](https://github.com/kwaroran/RisuAI/assets/81911204/4cd463eb-18c8-4cbb-a031-8afd396a429f)

**Comment by kwaroran** [comment]
english, please.
