### ISSUE TITLE
Problem with 50 tokens received when using the Kobold API.

### ISSUE THREAD

**Issue by PassingFace** [kwaroran/RisuAI#232]
![image](https://github.com/kwaroran/RisuAI/assets/141846006/2e668881-1181-45a2-bd17-cb34efc2314a)

![image](https://github.com/kwaroran/RisuAI/assets/141846006/5f859152-6953-4201-913c-bb55024dddc0)

![image](https://github.com/kwaroran/RisuAI/assets/141846006/99d7dcd7-65bc-4523-bb18-c12d6ca873dd)
https://arca.live/b/characterai/77484263

After modifying it as above, the set tokens of 50 or more are properly received.
Please apply officially.

**Comment by perkel666** [comment]
Same here looking kobold.ccp version. It doesn't generate more than 50 tokens

**Comment by kwaroran** [comment]
- [ ]
