### ISSUE TITLE
Is it possible to automatically apply the Google Drive backup error workaround to the risu itself?

### ISSUE THREAD

**Issue by ookk36930** [kwaroran/RisuAI#250]
https://arca.live/b/characterai/82455337

해당 글에 나와있는 방법대로 하면 리스 구드백업이 오류없이 잘 불러와지는데요 리스자체에 자동으로 오디오나 영상이나 여러 오류를 일으키는 파일들을 업로드할때 자동으로 확장자이름만 .png로 바꾸게 하는게 어떨까요? 그럼 백업문제는 다 해결될거같은데

**Comment by ookk36930** [comment]
기존봇도 문제없게 하기위해 문제되는 에셋이나 감정봇도 임포트할때 확장자이름만 자동 png로 바꾸고 임포트되는 시스템도 있으면 정말 좋겠습니다.

**Comment by ookk36930** [comment]
추가로 gif처럼 png로 바꾸고 업로드하고 봇카드를 내보내고 불러왔을때 png로 바꾼 gif가 안움직이는 이런 부분들도 고쳐지면 좋겠네요...

**Comment by kwaroran** [comment]
이미 그렇게 하고 있습니다만, 고쳐지지 않습니다.
