### ISSUE TITLE
RuntimeError with Claude model on Risu iOS web version

### ISSUE THREAD

**Issue by MinG-Gith** [kwaroran/RisuAI#272]
In a recent update, When using the web version of Risu on iOS and selecting the claude model for a conversation, the following error message appears: RuntimeError: Aborted(CompileError: WebAssembly.Module doesn't parse at byte 2241: invalid opcode 253, in function at index 780). Build with -sASSERTIONS for more info. 
Selecting the openai or other models does not produce an error. I can run the same configuration normally on my computer.

**Comment by kwaroran** [comment]
If are using an older version of Safari that does not support some of WASM API, that occurs. We do not consider this a bug.
