### ISSUE TITLE
UX Enhancement Suggestions

### ISSUE THREAD

**Issue by udada63** [kwaroran/RisuAI#31]
![2023-05-10 084621](https://github.com/kwaroran/RisuAI/assets/77280886/6f8e08ac-27a8-430c-a8c7-09199a48798c)

**Rational:**
It's rather tiring to press that three-line icon to surface the options icon(gear), when I am often modifying User/Bot/Advanced Settings.

**Request:**
- Allow us to toggle always show the options icon(gear) at the option.

Or

- How about making a new side tab on the right side (like NAI?) and letting us quickly access it as an options tab.

**ETC:**

- I would appreciate to "go back" or "cancel" button on the catalog page.
- Can we get drag and drop function with group chat? I sometimes get to remove and add character quickly with large RPG projects

**Comment by Alwaysfindtheway** [comment]
I think it's a good idea.
In addition to that, is it possible to indicate somewhere on the top or left side what preset is currently being used?
I see a lot of users trying to use reverse proxy and then realize they're using Nat.dev or their own paid API.
