### ISSUE TITLE
로어북 설정 중 "단어 단위 매칭" 기능이 작동하지 않는 것 같습니다.

### ISSUE THREAD

**Issue by dhrgusdlrns** [kwaroran/RisuAI#340]
정확히는 해당 단어가 키워드로 들어있음에도 불구하고 리퀘스트에 포함되지 않습니다.
LoreBook+나 재귀 검색 기능을 체크해보기도 했지만 의도한 대로 작동하지 않는 것 같습니다.

사용 모델: 클로드 3 오푸스

**Comment by kwaroran** [comment]
단어 단위 매칭기능은 정상 작동 중입니다. 문자열이 대소문자 구별하고, 스페이스로 나뉘어져야 제대로 구분됩니다.
