### ISSUE TITLE
Virus detected in 1.95.4 .MSI

### ISSUE THREAD

**Issue by Steel-skull** [kwaroran/RisuAI#368]
just a heads up, I don't know why but I cannot download it at the moment due to a virus popup. cannot download on any chrome based platform.

<img width="320" alt="image" src="https://github.com/kwaroran/RisuAI/assets/79706171/0bf7f056-552b-4618-8e60-fea8d7ad397c">

**Comment by kwaroran** [comment]
Just another virs misdetection, would be fixed on 1.95.5

**Comment by Steel-skull** [comment]
> Just another virs misdetection, would be fixed on 1.95.5

i though as much wanted to make sure people didnt get scared off by this
