### ISSUE TITLE
Risu doesn't initalize if it is fresh start

### ISSUE THREAD

**Issue by random-username-423** [kwaroran/RisuAI#384]
Phenomenon:
1. User enters risuai for the first time.
2. Webpage shows risu icon.
3. Then, it shows nothing. everything is stopped at blue background screen.

Error message from console:
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'chaId')
>     at L (index-nM1o2-Uh.js:2877:18795)
>     at create_fragment$T (index-nM1o2-Uh.js:2877:18826)
>     at init (index-nM1o2-Uh.js:5:31815)
>     at new Chat (index-nM1o2-Uh.js:2877:25550)
>     at Array.create_else_block_1$7 (index-nM1o2-Uh.js:2942:21097)
>     at Array.create_else_block$d (index-nM1o2-Uh.js:2942:20125)
>     at Object.p (index-nM1o2-Uh.js:2942:29973)
>     at update$1 (index-nM1o2-Uh.js:5:28469)
>     at flush (index-nM1o2-Uh.js:5:27846)

This error is reproducible by entering risuai.xyz with Incognito Window.
This error starts to appear since yesterday.

**Comment by existmaster** [comment]
I am reproducing the same problem.

**Comment by random-username-423** [comment]
This issue has been resolved by commit https://github.com/kwaroran/RisuAI/commit/8d91267c69bab32232b5bdbe5a784e7ed98b63a4, version 1.100.0
