### ISSUE TITLE
Suggestion: Diversify LoreBook injection points

### ISSUE THREAD

**Issue by bangonicdd** [kwaroran/RisuAI#422]
Currently, LoreBook can access only two kinds of places, including the '＠＠end' keyword. 

What do you think of the idea of additional placeholders in LoreBooks that can be placed elsewhere in the prompt template, or additional reserved words for other specific places like '＠＠end' (e.g. after global notes)?

Please let me know your thoughts on this.

**Comment by kwaroran** [comment]
We had already solved that problem in https://github.com/kwaroran/character-card-spec-v3/blob/main/SPEC_V3.md, and implemented in 1.106.0
