### ISSUE TITLE
CharX export is not following CCV3 specification

### ISSUE THREAD

**Issue by LightningHyperBlaze45654** [kwaroran/RisuAI#497]
According to [CCV3](https://github.com/kwaroran/character-card-spec-v3/blob/main/SPEC_V3.md)
  CHARX file SHOULD follow this rule saving the assets:
   - if the asset is a image like .png or .avif, the asset SHOULD be saved at 'assets/{type}/images/' directory.

![image](https://github.com/kwaroran/RisuAI/assets/73149145/cb01f778-5538-4c85-bd35-bd6da579e185)
But, the actual .charx file exported image assets to assets/other/ directory. 
Is this intentional?

**Comment by kwaroran** [comment]
It was not intentional, fixed in ec97e17ad58044c1112789b95dc3be97478049ce
Though, since it is *SHOULD*, its just a recommendation in the spec.
