### ISSUE TITLE
{"message":"invalid request: message must be at least 1 token long or tool results must be specified."} When using cohere

### ISSUE THREAD

**Issue by o0FireBlade0o** [kwaroran/RisuAI#504]
When using Cohere, clicking the "Send Message" button will result in the following error message:
{"message":"invalid request: message must be at least 1 token long or tool results must be specified."} 

There is no such issue when using OpenAI, and I don't know why.

**Comment by Jorsall1** [comment]
I have the same issue

**Comment by faisalshk** [comment]
I also have the same issue

**Comment by beverm2391** [comment]
same

**Comment by kwaroran** [comment]
Cohee enforces a specific format. If you do not follow that format, Cohee will reject it and an error like this will occur. This can be resolved by modifying the prompt, and is not a Risu error.
