### ISSUE TITLE
[bug] I can't create a character...

### ISSUE THREAD

**Issue by ookk36930** [kwaroran/RisuAI#51]
When I press Create Character, nothing happens. I see a very small space in the bottom left corner, but it doesn't respond when I press it.

**Comment by kwaroran** [comment]
can you tell me you environment? like os and browser

**Comment by ookk36930** [comment]
window 10 browser risu

**Comment by kwaroran** [comment]
what browser

**Comment by ookk36930** [comment]
chrome

**Comment by kwaroran** [comment]
did you tried restarting your browser?

**Comment by ookk36930** [comment]
yes

**Comment by kwaroran** [comment]
does app the freezes?

**Comment by ookk36930** [comment]
No, you get a very small whitespace with the text and that's it.

**Comment by tommisis** [comment]
Disable any adblocker for risuai.xyz
