### ISSUE TITLE
MacOS x64 client shows a completely blank window

### ISSUE THREAD

**Issue by shoebillanon** [kwaroran/RisuAI#571]
Running MacOS Mojave 10.14.6, fresh install of the Risu app directly from the risuai.net site

<img width="1136" alt="Screenshot 2024-07-14 at 00 14 26" src="https://github.com/user-attachments/assets/9ecc7d99-bdef-4d9d-81aa-056dc6010380">

**Comment by Asherathe** [comment]
The Linux version starts normally, but freezes and/or goes to a blank screen just like this when clicking through menu options too quickly, clicking ChatBot/Others or going into the character card/Character Display. The last AppImage version that worked right was 129.0.1. Everything newer, including the current version is basically unusable. From what I've read, it seems like a problem with some versions of webkitgtk.
