### ISSUE TITLE
NovelAI API Migration notice

### ISSUE THREAD

**Issue by lun-4** [kwaroran/RisuAI#611]
hello, we've been working on a faster/more stable inference stack which involves the creation of a new textgen API endpoint.
we have been in talks with other third-party frontends to carry out the migration from their side to prevent surprises.

TL;DR
 - for inference **of Kayra**, start to use https://text.novelai.net instead of https://api.novelai.net
 - **on September 30th, 2024, Kayra will be unavailable from api.novelai.net, requiring text.novelai.net**
 - Clio (and other models) are to be migrated to the new text API at a later date.
 - documentation available on https://api.novelai.net/docs and https://text.novelai.net/docs/index.html

extra notes regarding the migration (more information on the textgen docs themselves):
 - have nerdstash v1 and v2 (for Clio and Kayra respectively) available for context management
 - you need to still call `https://api.novelai.net/user/subscription` to know the maximum settings allowed to the current api key, because:
 - context size validation is strict (instead of stripping tokens when using more than allowed, it will emit an explicit error)
 - as an example, SillyTavern has migrated in their `staging` branch with the following commits:
   - https://github.com/SillyTavern/SillyTavern/commit/bdc335d238363b4e4adc2987c01972510033efc7
   - https://github.com/SillyTavern/SillyTavern/commit/2b904bb1707141e3484484f2d6dacf81cf471a46
   - https://github.com/SillyTavern/SillyTavern/commit/b21ba850c0e4837a652770c36d83525c05dd1121
   - https://github.com/SillyTavern/SillyTavern/commit/9010880b64c4710768b6f16cfc98cc0b10b1247e

**Comment by kwaroran** [comment]
7ba6a81ff0789578011fe8eb04549655b0052be5
