### ISSUE TITLE
question: char compatibility/migration to risu

### ISSUE THREAD

**Issue by steve02081504** [kwaroran/RisuAI#624]
Hi, I'm a character author. Considering that risu offers more features than ST, such as `if` macros and embedded png resources, I'm interested in making my character compatible with risu or, depending on the situation, migrating it to risu (abandoning ST support).

However, I've gone through the documentation and couldn't find answers to certain questions, so I'd like to ask here.

1. Does risu support recursive scanning of WIbooks? How do I set it up and trigger this content?
   My character relies almost entirely on recursive scanning of WIbooks to generate prompts, but I haven't seen anything similar in my brief experiments with risu. However, I noticed that the `hidden_key` macro in the wiki seems to mention something about recursive scanning. Is there a detailed explanation of recursion?
2. Is there a macro in risu that can randomly select N items (instead of 1) from an array, similar to drawing multiple cards from a deck?
   Something like `{{randomN:N:items}}`, I would really like a similar feature.
3. In risu, can a character set variables through its output?
   In ST, setting variables through character output is quite troublesome (because character output doesn't trigger macro expansion). I'd like to know if there's a simpler way to do this in risu.
4. Is there a way to prevent users from viewing WIbooks in risu?
   I don't want users to see the contents of WIbooks, so I've used [some trick](https://github.com/steve02081504/GentianAphrodite/blob/68d2bd27d771cb0f723c6a08711658bb9901c4fe/src/WIbookCrypto.mjs#L139) to make my character's WIbook invisible in ST but still functional. It seems that such WIbooks cannot be imported into risu. I'd like to know if there are similar methods in risu.

**Comment by kwaroran** [comment]
1. Risu has recursive scanning in character's settings.
2. Not yet, but you can implement by using `{{#each}}` keyword.
3. Yes, use `{{setvar::KEY::VALUE}}`
4. Not yet.

**Comment by steve02081504** [comment]
Thank you for your reply, but I woke up with more questions, so I thought I'd ask a few more.

1. In my experience last night, it seems that WI entries in risu don't have [4 logical options](https://github.com/steve02081504/GentianAphrodite/blob/3e415fea0fd8bbe5dc391a02fc755aaf9fc002c4/src/engine/world_info.mjs#L68L75), but my character uses all 4 existing logical options currently supported by ST. Is there a plan to support them further in the future, or did I just miss the setting?
2. Since you mentioned that the `#each` macro can be used to implement such a custom function, I'd like to ask if I can define custom functions within macros for logic reuse?
   For example, `#function::func_name::arg_list`?
3. My character also uses [delay|sticky|cooldown](https://github.com/steve02081504/GentianAphrodite/blob/3e415fea0fd8bbe5dc391a02fc755aaf9fc002c4/src/engine/world_info.mjs#L54L62) in ST. Does risu already support or will support these in the future?
4. It seems that risu doesn't import the [regex for embedded png files(`charData.extensions.regex_scripts`)](https://github.com/steve02081504/GentianAphrodite/blob/3e415fea0fd8bbe5dc391a02fc755aaf9fc002c4/src/cardinfo.mjs#L428) in ST. Is there a possibility of supporting this in the future?

**Comment by kwaroran** [comment]
1, 3. Risu uses lorebook decorators for it. checkout [Decorators]( https://kwaroran.github.io/docs/characterconfig/lorebook/#decorators). though, delay, sticky and cooldown aren't here yet.
2, 4 . Not right now, but I plan to implement later.
5. On Risu, you don't even have to do that. We have lorebook sections for each characters. just make a lorebook in specific char.
6. Yes.

**Comment by steve02081504** [comment]
> Risu uses lorebook decorators for it. checkout [Decorators](https://kwaroran.github.io/docs/characterconfig/lorebook/#decorators). though, delay, sticky and cooldown aren't here yet.

looks like `activate_only_after` decorator does same work as `delay` so guess you dont need to impl it! (Maybe we can set an alias for it? don't have a concrete idea.)

> just make a lorebook in specific char. 

I'm not sure if you misunderstood what I'm trying to do. You can refer to https://github.com/SillyTavern/SillyTavern-Docs/pull/99/files. I'm trying to use this feature to activate certain keys only when spoken by a specific character, and an entry may have multiple keys for different character matchs.
For example, this entry in git:
![图片](https://github.com/user-attachments/assets/3d8c1aac-eb3a-4a92-ad17-6fa946affaf5)
It will be compiled into something like this after compilation
![图片](https://github.com/user-attachments/assets/d589c446-1638-4778-80da-649c4325e942)


> but I plan to implement later.

Thank you for your hard work!

I think you could consider creating a separate documentation page to introduce the differences and similarities between risu and ST (including those features that are supported in ST but not in risu but have alternatives) to help people who want to migrate their characters better understand these differences. This way, people like me won't have to bother you so many times.

Overall, the functional differences between risu and ST are much greater than I thought, but thank you for your patient introduction and guidance. Now I have a clearer understanding of the platform's features and am confident in quickly migrating my card from ST to risu when needed. However, due to the large differences (and the lack of good alternatives for some features), I may not start writing the relevant programs right now.

But thank you for your explanation, have a nice day!
