### ISSUE TITLE
a problem on inlay images after 1.36.1 update

### ISSUE THREAD

**Issue by 4466644** [kwaroran/RisuAI#643]
I had been using a lot of image generation function with inlay images. 
And, when I applied 1.36.1 update, something strange happened.
![image](https://github.com/user-attachments/assets/51b94f94-f439-4807-a14a-3597184f8071)
These inlay images started to appear like this.
![image](https://github.com/user-attachments/assets/56704969-5dcd-46a2-a54f-af3c242c705d)
So, I tried to make another inlay image, and it looks like inlay images after the update look fine.
![image](https://github.com/user-attachments/assets/c9367bbb-8881-48a8-97df-6bb6b21903c1)
When I went back to previous version, 1.35.0, the inlay image before update started to appear well.
![image](https://github.com/user-attachments/assets/8434fa60-fad5-4dd6-8a3d-ea4322175e6a)
But, this time, the inlay images after update started to appear like this.
Will there be a way to solve this problem? I have been getting a lot of inlay images before update, and I don't want to lose them all.
Thank you.

**Comment by kwaroran** [comment]
This is unfixable, due to the difference in handling web storage between Tauri v1 and v2.
