### ISSUE TITLE
How to install RisuAI linux version in termux?

### ISSUE THREAD

**Issue by KingXMAX** [kwaroran/RisuAI#646]
Hi, i'm new to RisuAI and i want to use it on my android phone, and since the android version is currently unavailable, i would need a guide to install Risu (linux version) on termux and how to connect to it afterwards to get started. Thank you in advance.

**Comment by kwaroran** [comment]
Termux isn't supported by RisuAI, since it requires Sharp library, which doesn't allow terminux. to use in mobile, we recommend using the web version instead of node version.
