### ISSUE TITLE
Add the function of externally passing in API and key to the web page

### ISSUE THREAD

**Issue by Pevernow** [kwaroran/RisuAI#667]
In order to enhance the convenience of using the API site,
 it is necessary to provide a one-click function to pass in the API address and key through URL parameters,
 which allows customers to use the API services they purchased with one click.

**Comment by kwaroran** [comment]
I view this very negatively as it can be used for scams if it passes a scam URL.

**Comment by Pevernow** [comment]
> I view this very negatively as it can be used for scams if it passes a scam URL.

I think you got my meaning wrong.
This is not to promote scam URLs, but to better integrate with third-party API services.
It just allows risuai to use the purchased API link and key with one click, making it more convenient for users.
There is no need to go to any third-party website from risuai.

If the incoming API link is fake, nothing will happen except that the service is unavailable.

**Comment by Pevernow** [comment]
In fact, many clients have already provided this service, such as the famous Lobechat or opencat.

After users purchase services from third-party API service providers, they can click a link such as https://risuai.xyz/?base_url=xxxxx.ai/v1&key=sk-xxxxxxx, open risuai with one click, and enjoy the services they purchased, that's all.

There is no fraud.

**Comment by Pevernow** [comment]
If that doesn't work, then I can only consider migrating to sillytarven to provide services to customers. 

Sorry.
