### ISSUE TITLE
RisuAI Discord Server

### ISSUE THREAD

**Issue by Devon2311** [kwaroran/RisuAI#70]
Hey there! I have a suggestion that could greatly benefit your UI. How about creating a Discord server where people can provide feedback and share their thoughts? It would be a fantastic way to engage with users who may not have a GitHub account. Discord is widely used, and many individuals prefer to discuss their issues and concerns there. By establishing a Discord server, you would not only address this common problem but also foster a sense of community around your UI. This, in turn, would contribute to increased popularity, as other UIs with Discord servers have successfully achieved. I hope you find this idea helpful!

**Comment by kwaroran** [comment]
It is in plan, bur It might take some time

**Comment by kwaroran** [comment]
Made it, check readme
